# Generated by Django 2.2.2 on 2019-06-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this book', to='shelfapp.Category'),
        ),
    ]
