# Generated by Django 2.2.2 on 2019-06-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelfapp', '0004_auto_20190627_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='categories',
        ),
    ]
